default: &default
  adapter: postgresql
  encoding: unicode
  username: dev
  password: password
  port: 5432
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yulu_endpoints_development

test:
  <<: *default
  database: yulu_endpoints_test

production:
  adapter: cockroachdb
  port: 26257
  database: yulu
  url: <%= ENV['DATABASE_URL'] %>
